import { InspectionRecord } from './types';

export const INITIAL_RECORDS: InspectionRecord[] = [
  {
    id: 'INSP-2024-001',
    category: 'Inline',
    date: '2024-05-01',
    poNumber: 'PO-98231',
    styleNumber: 'TS-Basic-Crew',
    articleNumber: 'ART-5541',
    crdDate: '2024-05-15',
    buyer: 'H&M',
    color: 'Navy Blue',
    size: 'M',
    inspectedQuantity: 1000,
    criticalDefects: 10,
    majorDefects: 20,
    minorDefects: 20,
    shortage: 50,
    excess: 0,
    status: 'Pass',
    inspector: 'John Doe',
    remarks: 'Minor stitching issues found.',
  },
  {
    id: 'INSP-2024-002',
    category: 'Prefinal',
    date: '2024-05-01',
    poNumber: 'PO-33492',
    styleNumber: 'JN-Denim-Slim',
    articleNumber: 'ART-1032',
    crdDate: '2024-05-20',
    buyer: 'Zara',
    color: 'Washed Blue',
    size: '32',
    inspectedQuantity: 800,
    criticalDefects: 0,
    majorDefects: 10,
    minorDefects: 10,
    shortage: 20,
    excess: 0,
    status: 'Pass',
    inspector: 'Jane Smith',
    remarks: 'Consistent quality.',
  },
  {
    id: 'INSP-2024-003',
    category: 'Final',
    date: '2024-05-02',
    poNumber: 'PO-55102',
    styleNumber: 'JK-Winter-Puffer',
    articleNumber: 'ART-8890',
    crdDate: '2024-05-10',
    buyer: 'Nordstrom',
    color: 'Black',
    size: 'L',
    inspectedQuantity: 500,
    criticalDefects: 5,
    majorDefects: 25,
    minorDefects: 20,
    shortage: 50,
    excess: 0,
    status: 'Recheck',
    inspector: 'Mike Johnson',
    remarks: 'Zipper alignment issues.',
  },
  {
    id: 'INSP-2024-004',
    category: 'Inline',
    date: '2024-05-02',
    poNumber: 'PO-98231',
    styleNumber: 'TS-Basic-Crew',
    articleNumber: 'ART-5541',
    crdDate: '2024-05-15',
    buyer: 'H&M',
    color: 'White',
    size: 'L',
    inspectedQuantity: 1200,
    criticalDefects: 10,
    majorDefects: 50,
    minorDefects: 40,
    shortage: 100,
    excess: 0,
    status: 'Pass',
    inspector: 'John Doe',
    remarks: 'Staining on some pieces.',
  },
  {
    id: 'INSP-2024-005',
    category: 'Final',
    date: '2024-05-03',
    poNumber: 'PO-77421',
    styleNumber: 'DR-Summer-Floral',
    articleNumber: 'ART-3321',
    crdDate: '2024-05-25',
    buyer: 'Mango',
    color: 'Floral Print',
    size: 'S',
    inspectedQuantity: 600,
    criticalDefects: 50,
    majorDefects: 100,
    minorDefects: 50,
    shortage: 200,
    excess: 0,
    status: 'Fail',
    inspector: 'Sarah Williams',
    remarks: 'Major fabric defect observed.',
  },
];
