import { QualityRecord } from './types';

export const INITIAL_RECORDS: QualityRecord[] = [
  {
    id: 'PQ-2026-001',
    date: '2026-05-01',
    section: 'Sewing',
    unit: 'A',
    line: 'Line 01',
    shift: 'Day',
    style: 'TS-Basic-Crew',
    buyer: 'H&M',
    color: 'Navy Blue',
    size: 'M',
    inspectedQuantity: 1000,
    passedQuantity: 950,
    defectedQuantity: 50,
    reworkedQuantity: 40,
    rejectedQuantity: 10,
    status: 'Passed',
    inspector: 'John Doe',
    remarks: 'Minor stitching issues found.',
    topDefects: [{ type: 'Needle mark', count: 20 }, { type: 'Stitching error', count: 30 }],
  },
  {
    id: 'PQ-2026-002',
    date: '2026-05-01',
    section: 'Sewing',
    unit: 'A',
    line: 'Line 02',
    shift: 'Day',
    style: 'JN-Denim-Slim',
    buyer: 'Zara',
    color: 'Washed Blue',
    size: '32',
    inspectedQuantity: 800,
    passedQuantity: 780,
    defectedQuantity: 20,
    reworkedQuantity: 15,
    rejectedQuantity: 5,
    status: 'Passed',
    inspector: 'Jane Smith',
    remarks: 'Consistent quality.',
    topDefects: [{ type: 'Wash defect', count: 20 }],
  },
  {
    id: 'PQ-2026-003',
    date: '2026-05-02',
    section: 'Finishing',
    unit: 'A',
    line: 'Line 03',
    shift: 'Day',
    style: 'JK-Winter-Puffer',
    buyer: 'Nordstrom',
    color: 'Black',
    size: 'L',
    inspectedQuantity: 500,
    passedQuantity: 450,
    defectedQuantity: 50,
    reworkedQuantity: 20,
    rejectedQuantity: 30,
    status: 'Rework',
    inspector: 'Mike Johnson',
    remarks: 'Zipper alignment issues.',
    topDefects: [{ type: 'Zipper defect', count: 50 }],
  },
  {
    id: 'PQ-2026-004',
    date: '2026-05-02',
    section: 'Sewing',
    unit: 'A',
    line: 'Line 01',
    shift: 'Night',
    style: 'TS-Basic-Crew',
    buyer: 'H&M',
    color: 'White',
    size: 'L',
    inspectedQuantity: 1200,
    passedQuantity: 1100,
    defectedQuantity: 100,
    reworkedQuantity: 60,
    rejectedQuantity: 40,
    status: 'Passed',
    inspector: 'John Doe',
    remarks: 'Staining on some pieces.',
    topDefects: [{ type: 'Stain', count: 100 }],
  },
  {
    id: 'PQ-2026-005',
    date: '2026-05-03',
    section: 'Cutting',
    unit: 'A',
    line: 'Line 04',
    shift: 'Day',
    style: 'DR-Summer-Floral',
    buyer: 'Mango',
    color: 'Floral Print',
    size: 'S',
    inspectedQuantity: 600,
    passedQuantity: 400,
    defectedQuantity: 200,
    reworkedQuantity: 50,
    rejectedQuantity: 150,
    status: 'Rejected',
    inspector: 'Sarah Williams',
    remarks: 'Major fabric defect observed.',
    topDefects: [{ type: 'Fabric defect', count: 200 }],
  },
];
